name: oxoo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^3.0.0
  built_value: ^8.1.1
  carousel_slider: ^4.0.0
  chewie: ^1.0.0
  country_code_picker: ^3.0.0
#  credit_card_input_form: ^2.3.0
  cupertino_icons: ^1.0.3
  dio: ^5.3.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_downloader: ^1.9.1
  flutter_facebook_auth: ^5.0.8
  flutter_keyboard_visibility: ^5.0.2
#  flutter_mdns_plugin: ^0.0.3
  #flutter_playout: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.7
  #  fluttertoast: ^8.0.9
  get_it: ^7.1.3
  google_sign_in: ^6.1.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^1.0.1
  meta: ^1.3.0
  moor: ^4.4.1
  onesignal_flutter: ^3.4.1
  permission_handler: ^10.4.3
  pinput: ^2.2.11
  toast: ^0.3.0
  wakelock: ^0.6.2
#  webview_flutter_wkwebview: ^2.9.5
  flick_video_player: ^0.5.0
  provider: ^6.0.4

  share: ^2.0.4
  crypto: ^3.0.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.0.20
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^8.1.0
  video_player: ^2.2.7
  flutter_html:
  fab_circular_menu: ^1.0.2
  app_links: ^3.3.0
  scoped_model: ^2.0.0-nullsafety.0
  intl: ^0.18.1
  flutter_inapp_purchase: ^5.3.1
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.2
  firebase_in_app_messaging: ^0.7.0+7
  firebase_auth: ^4.1.4
  multicast_dns: ^0.3.2+2
  get: ^4.6.5
  shared_preferences: ^2.0.15
#  flutter_secure_storage: ^7.0.1
  flutter_secure_storage: ^8.0.0
  flutter_pagewise: ^2.0.4
  app_review: ^2.1.2+1
  kochava_tracker: ^2.1.1

#  smart_auth: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/android_launcher_icon.png"
  bloc_test: ^3.0.0
dependency_overrides:
  package_info_plus: any

#analyzer: ^0.41.0
flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Horizon
      fonts:
        - asset: fonts/Horizon.otf
        - asset: fonts/Horizon Italic.otf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500


  assets:
    - assets/light_splash_screen.gif
    - assets/logo.png
    - assets/android_launcher_icon.png
    - assets/drawer_icon/
    - assets/images/
    - assets/bottom_nav/
    - assets/images/ic_button_apple.png
    - assets/dark_splash_screen.gif


