// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTe0Js_7j7ZA5jjzb0WXhsvNLGk5xAiE',
    appId: '1:3297000991:android:923cd23794a95515c01f2a',
    messagingSenderId: '3297000991',
    projectId: 'idance2022-4d6d8',
    storageBucket: 'idance2022-4d6d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SyhcHkNaHUocv0EZbBu0jiHRp9Obfmc',
    appId: '1:3297000991:ios:d95f9cb65637dc8dc01f2a',
    messagingSenderId: '3297000991',
    projectId: 'idance2022-4d6d8',
    storageBucket: 'idance2022-4d6d8.appspot.com',
    androidClientId: '3297000991-0rjueillbkgnp5dpmh6ttmppmf3vmh8m.apps.googleusercontent.com',
    iosClientId: '3297000991-imajikjavk4338igpcuivhb90hh9bl14.apps.googleusercontent.com',
    iosBundleId: 'com.idance.hocnhayonline2023',
  );
}
